// This file is generated by scripts/generate-paths.ts
// Do not edit this file directly.

// @generated
// prettier-ignore
 

declare module "@@@next-static-paths" {
  interface Paths {
  "/": Record<never, never>,
  "/debug": Record<never, never>,
  "/debug/loading": Record<never, never>,
  "/discover": Record<never, never>
  }
}
