// This file is generated by npm run build:icons

export type IconName =
  | "android"
  | "gemini"
  | "ios"
  | "macos"
  | "nintendo-switch"
  | "playstation"
  | "v"
  | "windows"
  | "x"
  | "xbox";
